# # This is just an example, you should generate yours with nixos-generate-config and put it in here.
# {
#   boot.loader.systemd-boot.enable = true;

#   fileSystems."/" = {
#     device = "/dev/sda1";
#     fsType = "ext4";
#   };

#   # Set your system kind (needed for flakes)
#   nixpkgs.hostPlatform = "x86_64-linux";
# }


# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "dwc3_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/cd05548b-739d-410f-a959-d2c1de16c83a";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/b557dc0f-65d8-41ec-b963-58c102e89d98"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}